//
//  ListTransactionsRouter.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 15/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListTransactionsRoutingLogic {
	func routeToAddCard()
}

protocol ListTransactionsDataPassing {
	var dataStore: ListTransactionsDataStore? { get }
}

class ListTransactionsRouter: NSObject, ListTransactionsRoutingLogic, ListTransactionsDataPassing {
	weak var viewController: ListTransactionsViewController?
	var dataStore: ListTransactionsDataStore?
	
	// MARK: Routing
	
	func routeToAddCard() {
		let storyboard = UIStoryboard(name: "AddCard", bundle: nil)
		if let destinationVC = storyboard.instantiateViewController(withIdentifier: "AddCardViewController") as? AddCardViewController,
			let vc = self.viewController{
			self.navigateToAddCard(source: vc, destination: destinationVC)
		}
		
	}
	
	// MARK: Navigation
	
	func navigateToAddCard(source: ListTransactionsViewController, destination: AddCardViewController) {
		source.navigationController?.pushViewController(destination, animated: true)
	}
}
