//
//  ListTransactionsInteractor.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 15/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListTransactionsBusinessLogic {
	func doSomething(request: ListTransactions.Something.Request)
}

protocol ListTransactionsDataStore {
	//var name: String { get set }
}

class ListTransactionsInteractor: ListTransactionsBusinessLogic, ListTransactionsDataStore {
	var presenter: ListTransactionsPresentationLogic?
	var worker: ListTransactionsWorker?
	//var name: String = ""
	
	// MARK: Do something
	
	func doSomething(request: ListTransactions.Something.Request) {
		worker = ListTransactionsWorker()
		worker?.doSomeWork()
		
		let response = ListTransactions.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
