//
//  ListTransactionsPresenter.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 15/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListTransactionsPresentationLogic {
	func presentSomething(response: ListTransactions.Something.Response)
}

class ListTransactionsPresenter: ListTransactionsPresentationLogic {
	weak var viewController: ListTransactionsDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: ListTransactions.Something.Response) {
		let viewModel = ListTransactions.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
