# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Viajabessa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Viajabessa
  pod "ReachabilitySwift", '~> 4.1.0'
  pod "PromiseKit/CorePromise", "~> 6.0"

end
