//
//  AddCardViewController.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 15/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Caishen

protocol AddCardDisplayLogic: class {
	func displaySomething(viewModel: AddCard.Something.ViewModel)
}

class AddCardViewController: UIViewController, AddCardDisplayLogic {
	var interactor: AddCardBusinessLogic?
	var router: (NSObjectProtocol & AddCardRoutingLogic & AddCardDataPassing)?
	
	@IBOutlet weak var nameTextField: UITextField!
	@IBOutlet weak var numberTextField: NumberInputTextField!
	@IBOutlet weak var cvvTextField: CVCInputTextField!
	@IBOutlet weak var monthTextField: MonthInputTextField!
	@IBOutlet weak var yearTextField: YearInputTextField!
	
	
	// A card that is not nil when valid information has been entered in the text fields:
	var card: Card? {
		let number = numberTextField.cardNumber
		let cvc = CVC(rawValue: cvvTextField.text ?? "")
		let expiry = Expiry(month: monthTextField.text ?? "", year: yearTextField.text ?? "")
			?? Expiry.invalid
		
		let cardType = numberTextField.cardTypeRegister.cardType(for: numberTextField.cardNumber)
		if cardType.validate(cvc: cvc).union(cardType.validate(expiry: expiry)).union(cardType.validate(number: number)) == .Valid {
			return Card(number: number, cvc: cvc, expiry: expiry)
		} else {
			return nil
		}
	}
	
	// MARK: Object lifecycle
	
	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}
	
	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}
	
	// MARK: Setup
	
	private func setup() {
		let viewController = self
		let interactor = AddCardInteractor()
		let presenter = AddCardPresenter()
		let router = AddCardRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	// MARK: Routing
	
	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}
	
	// MARK: View lifecycle
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		self.numberTextField.numberInputTextFieldDelegate = self
		self.numberTextField.cardTypeRegister.register(cardType: CreditCard())
		
		self.cvvTextField.cardInfoTextFieldDelegate = self
		
		doSomething()
	}
	
	// MARK: Do something
	
	//@IBOutlet weak var nameTextField: UITextField!
	
	func doSomething() {
		let request = AddCard.Something.Request()
		interactor?.doSomething(request: request)
	}
	
	func displaySomething(viewModel: AddCard.Something.ViewModel) {
		//nameTextField.text = viewModel.name
	}
	
	@IBAction func saveCard(_ sender: Any? = nil) {
		if let holderName = self.nameTextField.text, holderName.isEmpty {
			print("SALVE O CARTÃO")
		} else {
			
		}
	}
	
}

extension AddCardViewController: NumberInputTextFieldDelegate, CardInfoTextFieldDelegate {
	func numberInputTextFieldDidComplete(_ numberInputTextField: NumberInputTextField) {
		cvvTextField.cardType = numberInputTextField.cardTypeRegister.cardType(for: numberInputTextField.cardNumber)
	}
	
	func numberInputTextFieldDidChangeText(_ numberInputTextField: NumberInputTextField) {
		
	}
	
	func textField(_ textField: UITextField, didEnterValidInfo: String) {
		switch textField {
		case is NumberInputTextField:
			self.cvvTextField.becomeFirstResponder()
		case is CVCInputTextField:
			self.monthTextField.becomeFirstResponder()
		case is MonthInputTextField:
			self.yearTextField.becomeFirstResponder()
		case is YearInputTextField:
			self.saveCard()
		default:
			break
		}
	}
	
	func textField(_ textField: UITextField, didEnterPartiallyValidInfo: String) {
		
	}
	
	func textField(_ textField: UITextField, didEnterOverflowInfo overFlowDigits: String) {
		
	}
}
