//
//  AddCardRouter.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 15/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddCardRoutingLogic {
	func routeToBuyTravelPackage()
}

protocol AddCardDataPassing {
	var dataStore: AddCardDataStore? { get }
}

class AddCardRouter: NSObject, AddCardRoutingLogic, AddCardDataPassing {
	weak var viewController: AddCardViewController?
	var dataStore: AddCardDataStore?
	
	// MARK: Routing
	
	func routeToBuyTravelPackage() {
		if let destinationVC = self.dataStore?.parentViewController as? BuyTravelPackageViewController {
			var destinationDS = destinationVC.router?.dataStore
			if let unwrappedDestDS = destinationVC.router?.dataStore, let dataStore = self.dataStore {
				destinationDS = unwrappedDestDS
				self.passDataToBuyTravelPackage(source: dataStore, destination: &destinationDS!)
			}
			
			self.navigateToBuyTravelPackage()
		}
		
	}
	
	// MARK: Navigation
	
	func navigateToBuyTravelPackage() {
		self.viewController?.navigationController?.popViewController(animated: true)
	}
	
	// MARK: Passing data
	
	func passDataToBuyTravelPackage(source: AddCardDataStore, destination: inout BuyTravelPackageDataStore) {
		destination.creditCard = source.creditCard
	}
}
