//
//  AddCardRouter.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 15/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddCardRoutingLogic {
  //func routeToSomewhere(_ segue: UIStoryboardSegue? = nil)
}

protocol AddCardDataPassing {
  var dataStore: AddCardDataStore? { get }
}

class AddCardRouter: NSObject, AddCardRoutingLogic, AddCardDataPassing {
  weak var viewController: AddCardViewController?
  var dataStore: AddCardDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(_ segue: UIStoryboardSegue? = nil) {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: AddCardViewController, destination: SomewhereViewController) {
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: AddCardDataStore, destination: inout SomewhereDataStore) {
  //  destination.name = source.name
  //}
}
