//
//  AddCardModels.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 15/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Caishen

enum AddCard {
	// MARK: Use cases
	
	enum Save {
		struct Request {
			var card: Card
		}
		
		struct Response {}
		
		struct ViewModel {}
	}
}
