//
//  BuyTravelPackageInteractor.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 14/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyTravelPackageBusinessLogic {
	func getPackageInfo(_ request: BuyTravelPackage.DisplayPackageInfo.Request)
}

protocol BuyTravelPackageDataStore {
	var selectedTravelPackage: TravelPackage! { get set }
}

class BuyTravelPackageInteractor: BuyTravelPackageBusinessLogic, BuyTravelPackageDataStore {
	var presenter: BuyTravelPackagePresentationLogic?
	var worker: BuyTravelPackageWorker?
	
	var selectedTravelPackage: TravelPackage!
	
	// MARK: Get Package info
	
	func getPackageInfo(_ request: BuyTravelPackage.DisplayPackageInfo.Request) {
		let response = BuyTravelPackage.DisplayPackageInfo.Response(
			title: self.selectedTravelPackage.name,
			value: self.selectedTravelPackage.value,
			description: self.selectedTravelPackage.description,
			image: self.selectedTravelPackage.image ?? #imageLiteral(resourceName: "logo")
		)
		presenter?.presentPackageInfo(response)
	}
}
