//
//  BuyTravelPackagePresenter.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 14/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyTravelPackagePresentationLogic {
	func presentSomething(response: BuyTravelPackage.Something.Response)
}

class BuyTravelPackagePresenter: BuyTravelPackagePresentationLogic {
	weak var viewController: BuyTravelPackageDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: BuyTravelPackage.Something.Response) {
		let viewModel = BuyTravelPackage.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
