//
//  BuyTravelPackagePresenter.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 14/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BuyTravelPackagePresentationLogic {
	func presentPackageInfo(_ response: BuyTravelPackage.DisplayPackageInfo.Response)
}

class BuyTravelPackagePresenter: BuyTravelPackagePresentationLogic {
	weak var viewController: BuyTravelPackageDisplayLogic?
	
	// MARK: Present Package Info
	
	func presentPackageInfo(_ response: BuyTravelPackage.DisplayPackageInfo.Response) {
		let viewModel = BuyTravelPackage.DisplayPackageInfo.ViewModel(
			title: response.title,
			price: "R$" + response.value.toString,
			description: response.description,
			image: response.image
		)
		viewController?.displayPackageInfo(viewModel)
	}
}
