//
//  BuyTravelPackageRouter.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 14/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BuyTravelPackageRoutingLogic {
	func routeToListTravelPackages()
}

protocol BuyTravelPackageDataPassing {
	var dataStore: BuyTravelPackageDataStore? { get }
}

class BuyTravelPackageRouter: NSObject, BuyTravelPackageRoutingLogic, BuyTravelPackageDataPassing {
	weak var viewController: BuyTravelPackageViewController?
	var dataStore: BuyTravelPackageDataStore?
	
	// MARK: Routing
	
	func routeToListTravelPackages() {
		self.viewController?.navigationController?.popViewController(animated: true)
	}
}
