//
//  ListTravelPackagesPresenter.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 13/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListTravelPackagesPresentationLogic {
	func presentSomething(response: ListTravelPackages.Something.Response)
}

class ListTravelPackagesPresenter: ListTravelPackagesPresentationLogic {
	weak var viewController: ListTravelPackagesDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: ListTravelPackages.Something.Response) {
		let viewModel = ListTravelPackages.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
