//
//  ListTravelPackagesInteractor.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 13/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListTravelPackagesBusinessLogic {
	func getAllTravelPackages(request: ListTravelPackages.ListTravelPackages.Request)
}

protocol ListTravelPackagesDataStore {
	
}

class ListTravelPackagesInteractor: ListTravelPackagesBusinessLogic, ListTravelPackagesDataStore {
	var presenter: ListTravelPackagesPresentationLogic?
	let worker = ViajabessaAPIWorker.shared
	
	// MARK: Get all Travel Packages
	
	var allTravelPackages: [TravelPackage] = []
	
	func getAllTravelPackages(request: ListTravelPackages.ListTravelPackages.Request) {
		var response = ListTravelPackages.ListTravelPackages.Response(packages: nil, error: nil)
		
		worker.getAllTravelPackages { (allTravelPackages, error) in
			if let allTravelPackages = allTravelPackages {
				self.allTravelPackages = allTravelPackages
				response.packages = self.allTravelPackages
			} else if let error = error {
				response.error = error
			} else {
				response.error = .Unknown
			}
			
			self.presenter?.presentTravelPackages(response: response)
		}
	}
}
