//
//  ListTravelPackagesInteractor.swift
//  Viajabessa
//
//  Created by Lucas Ferraço on 13/05/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListTravelPackagesBusinessLogic {
	func doSomething(request: ListTravelPackages.Something.Request)
}

protocol ListTravelPackagesDataStore {
	//var name: String { get set }
}

class ListTravelPackagesInteractor: ListTravelPackagesBusinessLogic, ListTravelPackagesDataStore {
	var presenter: ListTravelPackagesPresentationLogic?
	var worker: ListTravelPackagesWorker?
	//var name: String = ""
	
	// MARK: Do something
	
	func doSomething(request: ListTravelPackages.Something.Request) {
		worker = ListTravelPackagesWorker()
		worker?.doSomeWork()
		
		let response = ListTravelPackages.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
